# Generated by Django 5.2.3 on 2025-08-25 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='job_position',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='interview',
            old_name='interview_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='interview',
            old_name='interview_date',
            new_name='scheduled_at',
        ),
    ]
