# Generated by Django 5.2.3 on 2025-11-03 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='featured_image',
        ),
    ]
