# Generated by Django 5.2.3 on 2025-08-21 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
    ]
