# Generated by Django 5.2.3 on 2025-08-25 06:42

from django.db import migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_rename_job_position_interview_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='featured_image',
            field=models.ImageField(upload_to='job_images/', blank=True, null=True),
    ),
    ]
