# Generated by Django 5.2.1 on 2025-10-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_alter_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When the interview session actually started', null=True),
        ),
    ]
