# Generated by Django 5.2.3 on 2025-07-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='job_images/'),
        ),
    ]
