# Generated by Django 5.2.3 on 2025-08-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_job_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='department',
            field=models.CharField(choices=[('engineering', 'Engineering'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('hr', 'Human Resources'), ('finance', 'Finance'), ('operations', 'Operations'), ('design', 'Design'), ('product', 'Product'), ('customer_support', 'Customer Support'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('freelance', 'Freelance')], default='full_time', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='enable_ai_interview',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('lead', 'Lead/Manager'), ('executive', 'Executive')], default='mid', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='interview_duration',
            field=models.CharField(blank=True, choices=[('15', '15 minutes'), ('30', '30 minutes'), ('45', '45 minutes'), ('60', '60 minutes')], default='30', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='interview_question_count',
            field=models.IntegerField(blank=True, choices=[(5, '5 questions'), (8, '8 questions'), (10, '10 questions'), (12, '12 questions'), (15, '15 questions')], default=8, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.TextField(default='Not specified', help_text='Comma separated skills', max_length=500),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_max',
            field=models.IntegerField(default=80000, help_text='Maximum salary in your currency'),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_min',
            field=models.IntegerField(default=50000, help_text='Minimum salary in your currency'),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed'), ('expired', 'Expired'), ('filled', 'Position Filled')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed'), ('expired', 'Expired'), ('filled', 'Position Filled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
