# Generated by Django 5.2.1 on 2025-10-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_interview_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='interview_duration_minutes',
            field=models.IntegerField(choices=[(10, '10 minutes'), (15, '15 minutes'), (20, '20 minutes'), (30, '30 minutes')], default=15, help_text='Duration set by recruiter for this specific interview'),
        ),
        migrations.AlterField(
            model_name='job',
            name='interview_duration',
            field=models.CharField(blank=True, choices=[('10', '10 minutes'), ('15', '15 minutes'), ('20', '20 minutes'), ('30', '30 minutes')], default='15', max_length=20, null=True),
        ),
    ]
