# Generated by Django 5.2.3 on 2025-08-25 07:56

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_add_all_missing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='candidate_name',
            field=models.CharField(max_length=255, default='Unknown Candidate'),
        ),
        migrations.AddField(
            model_name='interview',
            name='candidate_email',
            field=models.EmailField(default='unknown@example.com'),
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_id',
            field=models.CharField(max_length=11, unique=True, blank=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='recording_data',
            field=models.TextField(blank=True, null=True, help_text="JSON data for recording information"),
        ),
        migrations.AddField(
            model_name='interview',
            name='recording_path',
            field=models.CharField(max_length=500, blank=True, null=True, help_text="Path to the recorded interview file"),
        ),
        migrations.AddField(
            model_name='interview',
            name='recording_duration',
            field=models.FloatField(blank=True, null=True, help_text="Duration of recording in seconds"),
        ),
        migrations.AddField(
            model_name='interview',
            name='is_recorded',
            field=models.BooleanField(default=False, help_text="Whether this interview was recorded"),
        ),
    ]
