# Generated by Django 5.2.3 on 2025-08-25 08:29

from django.db import migrations , models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_add_all_missing_fields'),
    ]

    operations = [
         # Change resume field to FileField
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(upload_to='resumes/', blank=True, null=True),
        ),
        # Change profile_picture field to ImageField
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(upload_to='profile_pics/', blank=True, null=True),
        ),
        # Allow bio to be null (instead of forcing empty string)
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(max_length=500, blank=True, null=True),
        ),
        # Make first_name optional
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=50, blank=True),
        ),
        # Make last_name optional
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=50, blank=True),
        ),
        # Make email optional
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, blank=True),
        ),
        # Make phone optional
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=20, blank=True),
        ),
        # Make location optional
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=100, blank=True),
        ),
        # Update skills field with help_text
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.CharField(max_length=300, blank=True, help_text="Separate skills with commas"),
        ),
        # Ensure OneToOne with user (AUTH_USER_MODEL)
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
