# Generated by Django 5.2.1 on 2025-08-12 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_profile_bio_profile_email_profile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='contact',
        ),
    ]
