# Generated by Django 5.2.1 on 2025-08-14 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0007_interview_model_update'),
    ]

    operations = [
        # Skip this migration for now - will be handled by model changes
    ]
