# Generated by Django 5.2.1 on 2025-08-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0008_auto_20250814_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(help_text='Upload your resume in PDF, DOC, or DOCX format (max 5MB)', upload_to='applications/resumes/'),
        ),
    ]
