# Generated by Django 5.2.3 on 2025-09-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0012_fix_candidate_constraint_sql'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('expired', 'Expired'), ('filled', 'Position Filled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('internship', 'Internship'), ('freelance', 'Freelance')], default='full_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('expired', 'Expired'), ('filled', 'Position Filled')], default='active', max_length=20),
        ),
    ]
