# Generated by Django 5.2.1 on 2025-09-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0013_alter_application_status_alter_job_employment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='ai_feedback',
            field=models.TextField(blank=True, help_text='AI-generated feedback about the candidate', null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='answers_given',
            field=models.TextField(blank=True, help_text='JSON data of candidate answers', null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='communication_score',
            field=models.FloatField(blank=True, help_text='Communication skills score out of 10', null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the interview was completed', null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='overall_score',
            field=models.FloatField(blank=True, help_text='Overall interview score out of 10', null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='problem_solving_score',
            field=models.FloatField(blank=True, help_text='Problem solving score out of 10', null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='questions_asked',
            field=models.TextField(blank=True, help_text='JSON data of questions asked during interview', null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('highly_recommended', 'Highly Recommended'), ('recommended', 'Recommended'), ('maybe', 'Maybe'), ('not_recommended', 'Not Recommended')], help_text='AI recommendation for hiring', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='results_generated_at',
            field=models.DateTimeField(blank=True, help_text='When AI results were generated', null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='technical_score',
            field=models.FloatField(blank=True, help_text='Technical skills score out of 10', null=True),
        ),
    ]
