# Generated by Django 5.2.3 on 2025-08-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0020_fix_duplicate_uuids'),
        ('jobapp', '0021_fix_interview_model'),
    ]

    operations = [
    ]
