# Generated by Django 5.2.3 on 2025-08-17 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0022_fix_interview_candidate_field'),
        ('jobapp', '0022_merge_20250817_2021'),
    ]

    operations = [
    ]
