# Generated by Django 5.2.3 on 2025-08-17 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0023_fix_candidate_id_column'),
        ('jobapp', '0023_merge_20250817_2052'),
    ]

    operations = [
    ]
