# Generated by Django 5.2.3 on 2025-08-17 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0024_add_candidate_id_column'),
        ('jobapp', '0024_merge_20250817_2100'),
    ]

    operations = [
    ]
