# Generated by Django 5.2.1 on 2025-08-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0025_merge_20250817_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='is_recorded',
            field=models.BooleanField(default=False, help_text='Whether this interview was recorded'),
        ),
        migrations.AddField(
            model_name='interview',
            name='recording_data',
            field=models.TextField(blank=True, help_text='JSON data for recording information', null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='recording_duration',
            field=models.FloatField(blank=True, help_text='Duration of recording in seconds', null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='recording_path',
            field=models.CharField(blank=True, help_text='Path to the recorded interview file', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
